version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./sboms:/app/sboms
      - ./tmp:/app/tmp
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - API_SERVER_URL=http://dtrack-apiserver:8080  # Add this line to reference the API
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
