version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./sboms:/app/sboms  # Ensure this directory is writable
      - ./tmp:/app/tmp      # Ensure this directory is writable
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistent data for MongoDB

volumes:
  mongo-data:
